In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
df=pd.read_excel('Datasets/Online_Retail.xlsx')
df.head()

  InvoiceNo StockCode                          Description  ...  UnitPrice CustomerID         Country
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER  ...       2.55    17850.0  United Kingdom
1    536365     71053                  WHITE METAL LANTERN  ...       3.39    17850.0  United Kingdom
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER  ...       2.75    17850.0  United Kingdom
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE  ...       3.39    17850.0  United Kingdom
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.  ...       3.39    17850.0  United Kingdom

[5 rows x 8 columns]

In [7]:
df['Description']=df['Description'].str.strip()
df.dropna(axis=0,subset=['InvoiceNo'],inplace=True)
df['InvoiceNo']=df['InvoiceNo'].astype('str')
df=df[-df['InvoiceNo'].str.contains('C')]
df

       InvoiceNo StockCode                          Description  ...  UnitPrice CustomerID         Country
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER  ...       2.55    17850.0  United Kingdom
1         536365     71053                  WHITE METAL LANTERN  ...       3.39    17850.0  United Kingdom
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER  ...       2.75    17850.0  United Kingdom
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE  ...       3.39    17850.0  United Kingdom
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.  ...       3.39    17850.0  United Kingdom
...          ...       ...                                  ...  ...        ...        ...             ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS  ...       0.85    12680.0          France
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL  ...       2.10    12680.0          France
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL  ...       4.15    12680.0          France
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE  ...       4.15    12680.0          France
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT  ...       4.95    12680.0          France

[532621 rows x 8 columns]

In [11]:
basket=(df[df['Country']=='France'].groupby(['InvoiceNo','Description',])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))
basket

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                          0.0  ...                              0.0
536852                          0.0  ...                              0.0
536974                          0.0  ...                              0.0
537065                          0.0  ...                              0.0
537463                          0.0  ...                              0.0
...                             ...  ...                              ...
580986                          0.0  ...                              0.0
581001                          0.0  ...                              0.0
581171                          0.0  ...                              0.0
581279                          0.0  ...                              0.0
581587                          0.0  ...                              0.0

[392 rows x 1563 columns]

In [13]:
def encode_units(x):
    if x<=0:
        return 0
    if x>=1:
        return 1
basket_sets=basket.applymap(encode_units)
basket_sets.drop('POSTAGE',inplace=True,axis=1)
basket_sets

C:\Users\MohamedAzar\AppData\Local\Temp\ipykernel_16432\68040096.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket_sets=basket.applymap(encode_units)

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                            0  ...                                0
536852                            0  ...                                0
536974                            0  ...                                0
537065                            0  ...                                0
537463                            0  ...                                0
...                             ...  ...                              ...
580986                            0  ...                                0
581001                            0  ...                                0
581171                            0  ...                                0
581279                            0  ...                                0
581587                            0  ...                                0

[392 rows x 1562 columns]

In [15]:
frequent_itemsets=apriori(basket_sets,min_support=0.07,use_colnames=True)
rules=association_rules(frequent_itemsets,metric='lift',min_threshold=1)
rules.head(20)

                             antecedents                           consequents  ...  certainty  kulczynski
0            (ALARM CLOCK BAKELIKE PINK)          (ALARM CLOCK BAKELIKE GREEN)  ...   0.695480    0.744079
1           (ALARM CLOCK BAKELIKE GREEN)           (ALARM CLOCK BAKELIKE PINK)  ...   0.736244    0.744079
2           (ALARM CLOCK BAKELIKE GREEN)            (ALARM CLOCK BAKELIKE RED)  ...   0.796590    0.826814
3             (ALARM CLOCK BAKELIKE RED)          (ALARM CLOCK BAKELIKE GREEN)  ...   0.820431    0.826814
4            (ALARM CLOCK BAKELIKE PINK)            (ALARM CLOCK BAKELIKE RED)  ...   0.696338    0.754392
5             (ALARM CLOCK BAKELIKE RED)           (ALARM CLOCK BAKELIKE PINK)  ...   0.759214    0.754392
6                   (SPACEBOY LUNCH BOX)                (DOLLY GIRL LUNCH BOX)  ...   0.524079    0.644689
7                 (DOLLY GIRL LUNCH BOX)                  (SPACEBOY LUNCH BOX)  ...   0.677656    0.644689
8        (PLASTERS IN TIN CIRCUS PARADE)            (PLASTERS IN TIN SPACEBOY)  ...   0.455263    0.589226
9             (PLASTERS IN TIN SPACEBOY)       (PLASTERS IN TIN CIRCUS PARADE)  ...   0.576914    0.589226
10       (PLASTERS IN TIN CIRCUS PARADE)    (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.524848    0.601538
11    (PLASTERS IN TIN WOODLAND ANIMALS)       (PLASTERS IN TIN CIRCUS PARADE)  ...   0.515429    0.601538
12    (PLASTERS IN TIN WOODLAND ANIMALS)            (PLASTERS IN TIN SPACEBOY)  ...   0.549943    0.685600
13            (PLASTERS IN TIN SPACEBOY)    (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.709630    0.685600
14         (SET/6 RED SPOTTY PAPER CUPS)  (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   0.701089    0.754986
15  (SET/20 RED RETROSPOT PAPER NAPKINS)         (SET/6 RED SPOTTY PAPER CUPS)  ...   0.732362    0.754986
16  (SET/20 RED RETROSPOT PAPER NAPKINS)       (SET/6 RED SPOTTY PAPER PLATES)  ...   0.735493    0.784615
17       (SET/6 RED SPOTTY PAPER PLATES)  (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   0.769412    0.784615
18         (SET/6 RED SPOTTY PAPER CUPS)       (SET/6 RED SPOTTY PAPER PLATES)  ...   0.872645    0.924444
19       (SET/6 RED SPOTTY PAPER PLATES)         (SET/6 RED SPOTTY PAPER CUPS)  ...   0.953609    0.924444

[20 rows x 14 columns]

In [17]:
rules[(rules['lift']>=6)&(rules['confidence']>=0.8)]

                                          antecedents                           consequents  ...  certainty  kulczynski
2                        (ALARM CLOCK BAKELIKE GREEN)            (ALARM CLOCK BAKELIKE RED)  ...   0.796590    0.826814
3                          (ALARM CLOCK BAKELIKE RED)          (ALARM CLOCK BAKELIKE GREEN)  ...   0.820431    0.826814
17                    (SET/6 RED SPOTTY PAPER PLATES)  (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   0.769412    0.784615
18                      (SET/6 RED SPOTTY PAPER CUPS)       (SET/6 RED SPOTTY PAPER PLATES)  ...   0.872645    0.924444
19                    (SET/6 RED SPOTTY PAPER PLATES)         (SET/6 RED SPOTTY PAPER CUPS)  ...   0.953609    0.924444
20  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...       (SET/6 RED SPOTTY PAPER PLATES)  ...   0.971345    0.877500
21  (SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...  (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   0.783824    0.781250
22  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...         (SET/6 RED SPOTTY PAPER CUPS)  ...   0.971006    0.848611

[8 rows x 14 columns]

In [19]:
#Transaction done in the uk
basket_UK=(df[df['Country']=="United Kingdom"]
          .groupby(['InvoiceNo','Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))

In [21]:
basket_UK

Description  *Boombox Ipod Classic  *USB Office Mirror Ball  ...  wrongly sold as sets  wrongly sold sets
InvoiceNo                                                    ...
536365                         0.0                      0.0  ...                   0.0                0.0
536366                         0.0                      0.0  ...                   0.0                0.0
536367                         0.0                      0.0  ...                   0.0                0.0
536368                         0.0                      0.0  ...                   0.0                0.0
536369                         0.0                      0.0  ...                   0.0                0.0
...                            ...                      ...  ...                   ...                ...
581585                         0.0                      0.0  ...                   0.0                0.0
581586                         0.0                      0.0  ...                   0.0                0.0
A563185                        0.0                      0.0  ...                   0.0                0.0
A563186                        0.0                      0.0  ...                   0.0                0.0
A563187                        0.0                      0.0  ...                   0.0                0.0

[18667 rows x 4175 columns]