In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
existing_df=pd.read_csv('Datasets/trans_us.csv',index_col=0,thousands=',')
existing_df

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
"TB prevalence, all forms (per 100 000 population per year)",,,,,,,,,,,,,,,,,,
Afghanistan,436,429,422,415,407,397,397,387,374,373,346,326,304,308,283,267,251,238
Albania,42,40,41,42,42,43,42,44,43,42,40,34,32,32,29,29,26,22
Algeria,45,44,44,43,43,42,43,44,45,46,48,49,50,51,52,53,55,56
American Samoa,42,14,4,18,17,22,0,25,12,8,8,6,5,6,9,11,9,5
Andorra,39,37,35,33,32,30,28,23,24,22,20,20,21,18,19,18,17,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis et Futuna,126,352,64,174,172,93,123,213,107,105,103,13,275,147,63,57,60,25
West Bank and Gaza,55,54,54,52,52,50,49,46,44,42,40,39,37,36,35,33,32,31
Yemen,265,261,263,253,250,244,233,207,194,175,164,154,149,146,138,137,135,130
Zambia,436,456,494,526,556,585,602,626,634,657,658,680,517,478,468,453,422,387
Zimbabwe,409,417,415,419,426,439,453,481,392,430,479,523,571,632,652,680,699,714

In [9]:
existing_df.index.names=['stations']
existing_df.columns.names=['year']
existing_df=existing_df.fillna(15)

In [11]:
existing_df.head()

year,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
stations,,,,,,,,,,,,,,,,,,
Afghanistan,436,429,422,415,407,397,397,387,374,373,346,326,304,308,283,267,251,238
Albania,42,40,41,42,42,43,42,44,43,42,40,34,32,32,29,29,26,22
Algeria,45,44,44,43,43,42,43,44,45,46,48,49,50,51,52,53,55,56
American Samoa,42,14,4,18,17,22,0,25,12,8,8,6,5,6,9,11,9,5
Andorra,39,37,35,33,32,30,28,23,24,22,20,20,21,18,19,18,17,19

In [13]:
existing_df.tail()

year,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
stations,,,,,,,,,,,,,,,,,,
Wallis et Futuna,126,352,64,174,172,93,123,213,107,105,103,13,275,147,63,57,60,25
West Bank and Gaza,55,54,54,52,52,50,49,46,44,42,40,39,37,36,35,33,32,31
Yemen,265,261,263,253,250,244,233,207,194,175,164,154,149,146,138,137,135,130
Zambia,436,456,494,526,556,585,602,626,634,657,658,680,517,478,468,453,422,387
Zimbabwe,409,417,415,419,426,439,453,481,392,430,479,523,571,632,652,680,699,714

In [15]:
existing_df=existing_df.fillna(15)

In [17]:
from sklearn.decomposition import PCA

In [19]:
pca=PCA(n_components=2)
pca.fit(existing_df)

PCA(n_components=2)

In [23]:
existing_2d=pca.transform(existing_df)
existing_df_2d=pd.DataFrame(existing_2d)
existing_df_2d.columns=['PC1','PC2']
existing_df_2d.head()

          PC1         PC2
0  732.215864  203.381494
1 -613.296510    4.715978
2 -569.303713  -36.837051
3 -717.082766    5.464696
4 -661.802241   11.037736

In [27]:
print(existing_df_2d.index==existing_df.index)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False]

In [29]:
existing_df_2d

             PC1         PC2
0     732.215864  203.381494
1    -613.296510    4.715978
2    -569.303713  -36.837051
3    -717.082766    5.464696
4    -661.802241   11.037736
..           ...         ...
202  -231.395787  123.076993
203  -585.225414   14.463482
204    59.256311  177.536948
205  1488.318012  -15.246686
206  1398.785663 -482.430628

[207 rows x 2 columns]

In [31]:
print(pca.explained_variance_ratio_)

[0.91808789 0.060556  ]